name: Container
on:
  pull_request:
    # branches:
    #   - main
    # types: [closed]

jobs:
  deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch base branch
        run: git fetch origin main:main

      - name: deploy
        run: |
          git diff --name-only origin/${{ github.base_ref }}...HEAD
          git diff --name-only origin/${{ github.base_ref }}...HEAD |grep ^projects |awk -F / '{print $2}'|sort |uniq
