name: Container
on:
  pull_request:
    # branches:
    #   - main
    # types: [closed]

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      prj_list: ${{ steps.check_update.outputs.upd_prj_list }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_update
        run: |
          upd_prj_list=`git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} |grep ^projects |awk -F / '{print $2}'|sort |uniq`
          echo $upd_prj_list
          echo "upd_prj_list=$upd_prj_list" >> $GITHUB_OUTPUT

  do_process:
    needs: check-update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.check-update.outputs.prj_list) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: |
          echo ${{ matrix.value }}